[general]
    group1 = [] # sample names for controls ["ctrl1", "ctrl2", "ctrl3"].
    group2 = [] # sample names for disease/case group ["case1", "case2", "case3"].
    comparison_name = "" # comparison name for output folder.
    analyses = [] # What analyses to run. Possible choices : ["degs", "as", "apa", "dmrs"].
    email = "" # Your e-mail address to receive notification.

[flair]
    conditionA = ""
    conditionB = ""

[apa_tool] # to change


[modkit]
    ctrl_bed = ""
    treatment_bed = ""